"use client";
import { useEffect, useState, type FormEvent } from "react";
import Navbar from "@/components/Navbar"; import Titulo from "@/components/Titulo";
type Historico={id:number;status:string;observacao:string|null;autor_nome:string;criado_em:string};
type Pedido={id:number;item:string;quantidade:number;unidade:string;justificativa:string;valor_estimado:number|null;status:string;solicitante_nome:string;criado_em:string;pode_gerenciar:boolean;historico:Historico[]};
type Compra={id:number;pedido_id:number|null;item:string;quantidade:number;unidade:string;fornecedor:string|null;valor_total:number;observacao:string|null;comprado_por_nome:string;data_compra:string};
const rotulos:Record<string,string>={solicitado:"Solicitado",aprovado:"Aprovado",rejeitado:"Rejeitado",comprado:"Comprado",cancelado:"Cancelado"};
export default function PedidosCompraPage(){const [pedidos,setPedidos]=useState<Pedido[]>([]),[compras,setCompras]=useState<Compra[]>([]),[erro,setErro]=useState(""),[salvando,setSalvando]=useState(false); const [item,setItem]=useState(""),[quantidade,setQuantidade]=useState("1"),[unidade,setUnidade]=useState("un"),[justificativa,setJustificativa]=useState(""),[valor,setValor]=useState("");
async function carregar(){const [rp,rc]=await Promise.all([fetch("/api/pedidos-compra"),fetch("/api/compras")]);const [dp,dc]=await Promise.all([rp.json(),rc.json()]);if(rp.ok)setPedidos(dp);else setErro(dp.detail??"Não foi possível carregar os pedidos.");if(rc.ok)setCompras(dc);} useEffect(()=>{void Promise.all([fetch("/api/pedidos-compra"),fetch("/api/compras")]).then(async([rp,rc])=>({rp,rc,dp:await rp.json(),dc:await rc.json()})).then(({rp,rc,dp,dc})=>{if(rp.ok)setPedidos(dp);else setErro(dp.detail??"Não foi possível carregar os pedidos.");if(rc.ok)setCompras(dc)})},[]);
async function criar(e:FormEvent){e.preventDefault();setSalvando(true);setErro("");const r=await fetch("/api/pedidos-compra",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({item,quantidade:Number(quantidade),unidade,justificativa,valor_estimado:valor?Number(valor):null})});const d=await r.json();setSalvando(false);if(!r.ok){setErro(d.detail??"Não foi possível criar o pedido.");return}setItem("");setJustificativa("");setValor("");await carregar()}
async function status(id:number,novo:string){const observacao=window.prompt("Observação (opcional):")||null;const r=await fetch(`/api/pedidos-compra/${id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:novo,observacao})});if(!r.ok){const d=await r.json();setErro(d.detail??"Não foi possível atualizar.");return}await carregar()}
async function gerarEstoque(p:Pedido){const localizacao=window.prompt("Localização no estoque (opcional):")||null;const r=await fetch("/api/estoque",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({nome:p.item,unidade:p.unidade,quantidade_inicial:p.quantidade,estoque_minimo:null,localizacao,pedido_id:p.id})});if(!r.ok){const d=await r.json();setErro(d.detail??"Não foi possível gerar o item de estoque.");return}window.alert("Item criado no estoque com a entrada vinculada a este pedido.")}
async function registrarCompra(p?:Pedido){const nome=window.prompt("Item comprado:",p?.item??"");if(!nome)return;const quantidadeComprada=Number(window.prompt("Quantidade:",String(p?.quantidade??1)));if(!quantidadeComprada)return;const unidadeComprada=window.prompt("Unidade:",p?.unidade??"un");if(!unidadeComprada)return;const valorTotal=Number(window.prompt("Valor total da compra:",String(p?.valor_estimado??0)));if(Number.isNaN(valorTotal))return;const fornecedor=window.prompt("Fornecedor (opcional):")||null;const observacao=window.prompt("Observação (opcional):")||null;const r=await fetch("/api/compras",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pedido_id:p?.id??null,item:nome,quantidade:quantidadeComprada,unidade:unidadeComprada,fornecedor,valor_total:valorTotal,observacao})});if(!r.ok){const d=await r.json();setErro(d.detail??"Não foi possível registrar a compra.");return}await carregar()}
return <main className="min-h-screen px-4 py-3 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><Navbar/><Titulo texto="Pedidos de compra" subtitulo="Solicitações, decisões e histórico de aquisição do condomínio."/>
<form onSubmit={criar} className="mt-8 grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-6"><input required value={item} onChange={e=>setItem(e.target.value)} placeholder="Item solicitado" className="input md:col-span-2"/><input required min="0.001" step="0.001" type="number" value={quantidade} onChange={e=>setQuantidade(e.target.value)} className="input"/><input required value={unidade} onChange={e=>setUnidade(e.target.value)} placeholder="Unidade" className="input"/><input min="0" step="0.01" type="number" value={valor} onChange={e=>setValor(e.target.value)} placeholder="Valor estimado" className="input md:col-span-2"/><textarea required value={justificativa} onChange={e=>setJustificativa(e.target.value)} placeholder="Justificativa" className="input md:col-span-5"/><button disabled={salvando} className="rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white disabled:opacity-50">{salvando?"Enviando...":"Solicitar"}</button></form>
<section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-slate-900">Compras realizadas</h2><p className="text-sm text-slate-500">Podem ser avulsas ou vinculadas a um pedido.</p></div>{pedidos.some(p=>p.pode_gerenciar)&&<button onClick={()=>void registrarCompra()} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-bold text-white">Registrar compra avulsa</button>}</div><div className="mt-4 grid gap-3 md:grid-cols-2">{compras.map(c=><div key={c.id} className="rounded-xl bg-slate-50 p-4"><div className="flex justify-between gap-2"><b>#{c.id} · {c.item}</b>{c.pedido_id&&<span className="text-xs font-bold text-blue-700">Pedido #{c.pedido_id}</span>}</div><p className="mt-1 text-sm text-slate-500">{c.quantidade} {c.unidade} · {c.fornecedor||"Fornecedor não informado"}</p><p className="mt-1 text-sm font-semibold">{c.valor_total.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</p><p className="mt-1 text-xs text-slate-400">{new Date(c.data_compra).toLocaleDateString("pt-BR")} · {c.comprado_por_nome}</p></div>)}</div></section>
{erro&&<p className="mt-4 rounded-xl bg-rose-50 p-4 text-rose-700">{erro}</p>}<div className="mt-6 space-y-4">{pedidos.map(p=><details key={p.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><summary className="cursor-pointer list-none"><div className="flex flex-wrap justify-between gap-3"><div><b>#{p.id} · {p.item}</b><p className="mt-1 text-sm text-slate-500">{p.quantidade} {p.unidade} · por {p.solicitante_nome} · {new Date(p.criado_em).toLocaleDateString("pt-BR")}</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-sm font-bold text-blue-700">{rotulos[p.status]}</span></div></summary><p className="mt-4 text-sm text-slate-700">{p.justificativa}</p>{p.valor_estimado!=null&&<p className="mt-1 text-sm">Estimativa: {p.valor_estimado.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</p>}{p.pode_gerenciar&&<div className="mt-4 flex flex-wrap gap-2">{["aprovado","rejeitado","comprado","cancelado"].map(s=><button key={s} onClick={()=>void status(p.id,s)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold hover:bg-slate-50">Marcar {rotulos[s].toLowerCase()}</button>)}{["aprovado","comprado"].includes(p.status)&&<button onClick={()=>void registrarCompra(p)} className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">Registrar compra deste pedido</button>}{p.status==="comprado"&&<button onClick={()=>void gerarEstoque(p)} className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">Gerar item no estoque</button>}</div>}<div className="mt-5 border-t border-slate-100 pt-4"><b className="text-sm">Histórico</b>{p.historico.map(h=><p key={h.id} className="mt-2 text-xs text-slate-500">{new Date(h.criado_em).toLocaleString("pt-BR")} · {rotulos[h.status]} · {h.autor_nome}{h.observacao?` — ${h.observacao}`:""}</p>)}</div></details>)}</div></div></main>}
