"use client";

import { useEffect, useState, type FormEvent } from "react";
import Navbar from "@/components/Navbar";
import Titulo from "@/components/Titulo";

type Tipo = "balancete" | "orcamento";
type Documento = { id:number; titulo:string; competencia:string|null; descricao:string|null; nome_arquivo:string; tamanho:number|null; publicado:boolean; pode_gerenciar:boolean };
const textos = { balancete:{ titulo:"Balancetes", subtitulo:"Consulte a prestação de contas periódica publicada pela gestão.", vazio:"Nenhum balancete publicado ou importado." }, orcamento:{ titulo:"Orçamentos", subtitulo:"Consulte previsões, propostas e orçamentos publicados pela gestão.", vazio:"Nenhum orçamento publicado ou importado." } };
const tamanhoLegivel=(bytes:number|null)=>bytes==null?"":bytes<1048576?`${Math.max(1,Math.round(bytes/1024))} KB`:`${(bytes/1048576).toFixed(1)} MB`;

export default function DocumentosFinanceiros({ tipo }: { tipo:Tipo }) {
  const [documentos,setDocumentos]=useState<Documento[]>([]),[editando,setEditando]=useState<Documento|null>(null),[erro,setErro]=useState(""),[carregando,setCarregando]=useState(true);
  async function carregar(){const r=await fetch(`/api/documentos-financeiros?tipo=${tipo}`,{cache:"no-store"});const d=await r.json();setCarregando(false);if(r.ok)setDocumentos(d);else setErro(d.detail??"Não foi possível carregar os documentos.")}
  useEffect(()=>{let ativo=true;void fetch(`/api/documentos-financeiros?tipo=${tipo}`,{cache:"no-store"}).then(async r=>({r,d:await r.json()})).then(({r,d})=>{if(!ativo)return;setCarregando(false);if(r.ok)setDocumentos(d);else setErro(d.detail??"Não foi possível carregar os documentos.")});return()=>{ativo=false}},[tipo]);
  async function salvar(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editando)return;const f=new FormData(e.currentTarget);const competencia=String(f.get("competencia")??"");const r=await fetch(`/api/documentos-financeiros/${editando.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({titulo:f.get("titulo"),competencia:competencia?`${competencia}-01`:null,descricao:f.get("descricao")||null,publicado:f.get("publicado")==="on"})});const d=await r.json();if(!r.ok){setErro(d.detail??"Não foi possível salvar o documento.");return}setEditando(null);await carregar()}
  const conteudo=textos[tipo];
  return <main className="min-h-screen px-4 py-3 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl"><Navbar/><Titulo texto={conteudo.titulo} subtitulo={conteudo.subtitulo}/>{erro&&<p className="mt-6 rounded-xl bg-rose-50 p-4 text-rose-700">{erro}</p>}{carregando?<p className="mt-8 text-slate-500">Carregando…</p>:documentos.length===0?<div className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">{conteudo.vazio}</div>:<div className="mt-8 grid gap-4">{documentos.map(d=><article key={d.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${d.publicado?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{d.publicado?"Publicado":"Pendente de revisão"}</span><h2 className="mt-3 text-lg font-bold text-slate-950">{d.titulo}</h2><p className="mt-1 text-sm text-slate-500">{d.competencia?new Date(`${d.competencia}T12:00:00`).toLocaleDateString("pt-BR",{month:"long",year:"numeric"}):"Competência não informada"} · {d.nome_arquivo} {tamanhoLegivel(d.tamanho)&&`· ${tamanhoLegivel(d.tamanho)}`}</p>{d.descricao&&<p className="mt-3 text-sm text-slate-600">{d.descricao}</p>}</div><div className="flex shrink-0 gap-2"><a href={`/api/documentos-financeiros/${d.id}/arquivo`} target="_blank" rel="noreferrer" className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">Abrir</a>{d.pode_gerenciar&&<button onClick={()=>setEditando(d)} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-bold text-slate-700">Revisar</button>}</div></div></article>)}</div>}
  {editando&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={salvar} className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-bold">Revisar {tipo}</h2><div className="mt-5 grid gap-4"><label className="text-sm font-bold">Título<input name="titulo" required minLength={3} maxLength={255} defaultValue={editando.titulo} className="input mt-1"/></label><label className="text-sm font-bold">Competência<input name="competencia" type="month" defaultValue={editando.competencia?.slice(0,7)??""} className="input mt-1"/></label><label className="text-sm font-bold">Descrição<textarea name="descricao" maxLength={4000} defaultValue={editando.descricao??""} className="input mt-1 min-h-24"/></label><label className="flex items-center gap-3 rounded-xl bg-slate-50 p-4 text-sm font-bold"><input name="publicado" type="checkbox" defaultChecked={editando.publicado} className="h-5 w-5"/>Disponibilizar para os moradores</label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setEditando(null)} className="rounded-xl px-4 py-2 font-semibold text-slate-600">Cancelar</button><button className="rounded-xl bg-blue-600 px-5 py-2 font-semibold text-white">Salvar</button></div></form></div>}</div></main>;
}
