"use client";

import { useEffect, useRef, useState, type FormEvent } from "react";
import Navbar from "@/components/Navbar";
import Titulo from "@/components/Titulo";
import ArvoreArquivos from "@/components/ArvoreArquivos";
import { useAcesso } from "@/src/hooks/useAcesso";

type Tipo = "balancete" | "orcamento" | "contrato" | "certificado" | "memorial";
type Documento = { id:number; titulo:string; competencia:string|null; descricao:string|null; nome_arquivo:string; caminho_relativo:string; mime_type?:string|null; tamanho:number|null; publicado:boolean; pode_gerenciar:boolean };
const textos = {
  balancete:{ titulo:"Balancetes", subtitulo:"Consulte a prestação de contas periódica publicada pela gestão.", vazio:"Nenhum balancete publicado ou importado." },
  orcamento:{ titulo:"Orçamentos", subtitulo:"Consulte previsões, propostas e orçamentos publicados pela gestão.", vazio:"Nenhum orçamento publicado ou importado." },
  contrato:{ titulo:"Contratos", subtitulo:"Consulte os contratos disponibilizados pela gestão do condomínio.", vazio:"Nenhum contrato publicado ou importado." },
  certificado:{ titulo:"Certificados", subtitulo:"Consulte certificados, licenças e documentos de conformidade do condomínio.", vazio:"Nenhum certificado publicado ou importado." },
  memorial:{ titulo:"Memorial", subtitulo:"Consulte memoriais e documentos técnicos do condomínio.", vazio:"Nenhum memorial publicado ou importado." },
};
const tamanhoLegivel=(bytes:number|null)=>bytes==null?"":bytes<1048576?`${Math.max(1,Math.round(bytes/1024))} KB`:`${(bytes/1048576).toFixed(1)} MB`;
function mensagemErro(dados:unknown,padrao:string){if(!dados||typeof dados!=="object")return padrao;const detalhe=(dados as {detail?:unknown}).detail;if(typeof detalhe==="string")return detalhe;if(Array.isArray(detalhe)){const mensagens=detalhe.map(item=>item&&typeof item==="object"&&typeof (item as {msg?:unknown}).msg==="string"?(item as {msg:string}).msg.replace(/^Value error,\s*/,""):null).filter(Boolean);if(mensagens.length)return mensagens.join(" ")}return padrao}
function normalizarCompetencia(valor:string){const texto=valor.trim();if(!texto)return null;const padraoIso=texto.match(/^(\d{4})-(\d{2})(?:-\d{2})?$/);if(padraoIso)return `${padraoIso[1]}-${padraoIso[2]}-01`;const padraoBrasil=texto.match(/^(\d{2})\/(\d{4})$/);if(padraoBrasil)return `${padraoBrasil[2]}-${padraoBrasil[1]}-01`;return texto}
function mesLocalAtual(){const agora=new Date();agora.setMinutes(agora.getMinutes()-agora.getTimezoneOffset());return agora.toISOString().slice(0,7)}

export default function DocumentosFinanceiros({ tipo }: { tipo:Tipo }) {
  const acesso=useAcesso(); const podeEditarDrive=acesso?.papeis.some(p=>["sindico","admin"].includes(p))??false;
  const [documentos,setDocumentos]=useState<Documento[]>([]),[editando,setEditando]=useState<Documento|null>(null),[visualizando,setVisualizando]=useState<Documento|null>(null),[erro,setErro]=useState(""),[carregando,setCarregando]=useState(true);
  const [pastas,setPastas]=useState<string[]>([]),[caminhoUpload,setCaminhoUpload]=useState(""); const inputArquivo=useRef<HTMLInputElement>(null);
  async function carregar(){const [r,re]=await Promise.all([fetch(`/api/documentos-financeiros?tipo=${tipo}`,{cache:"no-store"}),fetch(`/api/documentos-estrutura/${tipo}`,{cache:"no-store"})]);const d=await r.json();const de=await re.json().catch(()=>({pastas:[]}));setCarregando(false);if(r.ok)setDocumentos(d);else setErro(mensagemErro(d,"Não foi possível carregar os documentos."));if(re.ok)setPastas(de.pastas??[])}
  useEffect(()=>{let ativo=true;void Promise.all([fetch(`/api/documentos-financeiros?tipo=${tipo}`,{cache:"no-store"}),fetch(`/api/documentos-estrutura/${tipo}`,{cache:"no-store"})]).then(async([r,re])=>({r,re,d:await r.json(),de:await re.json().catch(()=>({pastas:[]}))})).then(({r,re,d,de})=>{if(!ativo)return;setCarregando(false);if(r.ok)setDocumentos(d);else setErro(mensagemErro(d,"Não foi possível carregar os documentos."));if(re.ok)setPastas(de.pastas??[])});return()=>{ativo=false}},[tipo]);
  async function criarPasta(){const valor=window.prompt("Caminho da nova pasta (ex.: Fornecedores/2026):")?.trim().replace(/^\/+|\/+$/g,"");if(!valor)return;const partes=valor.split("/");const nome=partes.pop()!;const r=await fetch("/api/documentos-pastas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tipo,caminho_pai:partes.join("/"),nome})});const d=await r.json().catch(()=>null);if(!r.ok){setErro(mensagemErro(d,"Não foi possível criar a pasta."));return}await carregar()}
  function escolherUpload(){const caminho=window.prompt("Pasta de destino relativa à raiz (deixe vazio para a raiz):","");if(caminho===null)return;setCaminhoUpload(caminho.trim().replace(/^\/+|\/+$/g,""));window.setTimeout(()=>inputArquivo.current?.click())}
  async function enviarArquivo(arquivo:File){const form=new FormData();form.append("caminho",caminhoUpload);form.append("arquivo",arquivo);const r=await fetch(`/api/documentos-upload/${tipo}`,{method:"POST",body:form});const d=await r.json().catch(()=>null);if(!r.ok){setErro(mensagemErro(d,"Não foi possível enviar o arquivo."));return}await carregar()}
  async function salvar(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editando)return;const f=new FormData(e.currentTarget);const competencia=normalizarCompetencia(String(f.get("competencia")??""));const r=await fetch(`/api/documentos-financeiros/${editando.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({titulo:f.get("titulo"),competencia,descricao:f.get("descricao")||null,publicado:f.get("publicado")==="on"})});const d=await r.json();if(!r.ok){setErro(mensagemErro(d,"Não foi possível salvar o documento."));return}setErro("");setEditando(null);await carregar()}
  const conteudo=textos[tipo];
  const usaCompetencia=tipo==="balancete"||tipo==="orcamento";
  return <main className="min-h-screen px-4 py-3 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl"><Navbar/><Titulo texto={conteudo.titulo} subtitulo={conteudo.subtitulo}/>{podeEditarDrive&&<div className="mt-6 flex flex-wrap gap-2"><button onClick={()=>void criarPasta()} className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold text-slate-700">Nova pasta</button><button onClick={escolherUpload} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white">Enviar arquivo</button><input ref={inputArquivo} type="file" className="sr-only" onChange={e=>{const arquivo=e.target.files?.[0];if(arquivo)void enviarArquivo(arquivo);e.target.value=""}}/></div>}{erro&&<p className="mt-6 rounded-xl bg-rose-50 p-4 text-rose-700">{erro}</p>}{carregando?<p className="mt-8 text-slate-500">Carregando…</p>:documentos.length===0&&pastas.length===0?<div className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">{conteudo.vazio}</div>:<div className="mt-8"><ArvoreArquivos preservarOrdem={tipo === "balancete"} arquivos={documentos} pastas={pastas} renderArquivo={d=>{const pdf=d.mime_type==="application/pdf"||d.nome_arquivo.toLowerCase().endsWith(".pdf");return <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${d.publicado?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{d.publicado?"Publicado":"Pendente"}</span><h2 className="truncate font-bold text-slate-950">{d.titulo}</h2></div><p className="mt-1 truncate text-xs text-slate-500">{usaCompetencia&&<>{d.competencia?new Date(`${d.competencia}T12:00:00`).toLocaleDateString("pt-BR",{month:"long",year:"numeric"}):"Competência não informada"} · </>}{d.nome_arquivo} {tamanhoLegivel(d.tamanho)&&`· ${tamanhoLegivel(d.tamanho)}`}</p>{d.descricao&&<p className="mt-1 text-xs text-slate-600">{d.descricao}</p>}</div><div className="flex shrink-0 gap-2">{pdf?<button onClick={()=>setVisualizando(d)} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white">Visualizar</button>:<a href={`/api/documentos-financeiros/${d.id}/arquivo`} target="_blank" rel="noreferrer" className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white">Abrir</a>}{d.pode_gerenciar&&<button onClick={()=>setEditando(d)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700">Revisar</button>}</div></div>}}/></div>}
  {editando&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={salvar} className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-bold">Revisar {tipo}</h2><div className="mt-5 grid gap-4"><label className="text-sm font-bold">Título<input name="titulo" required minLength={3} maxLength={255} defaultValue={editando.titulo} className="input mt-1"/></label>{usaCompetencia&&<label className="text-sm font-bold">Competência <span className="font-normal text-slate-500">(mês/ano)</span><input name="competencia" type="month" defaultValue={editando.competencia?.slice(0,7)??mesLocalAtual()} aria-describedby="dica-competencia" className="input mt-1"/><span id="dica-competencia" className="mt-1.5 block text-xs font-normal leading-5 text-slate-500">Período a que o documento se refere. Ex.: 08/2026.</span></label>}<label className="text-sm font-bold">Descrição<textarea name="descricao" maxLength={4000} defaultValue={editando.descricao??""} className="input mt-1 min-h-24"/></label><label className="flex items-center gap-3 rounded-xl bg-slate-50 p-4 text-sm font-bold"><input name="publicado" type="checkbox" defaultChecked={editando.publicado} className="h-5 w-5"/>Disponibilizar para os moradores</label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setEditando(null)} className="rounded-xl px-4 py-2 font-semibold text-slate-600">Cancelar</button><button className="rounded-xl bg-blue-600 px-5 py-2 font-semibold text-white">Salvar</button></div></form></div>}
  {visualizando&&<div className="fixed inset-0 z-50 flex flex-col bg-slate-950/70 p-2 backdrop-blur-sm sm:p-5"><div className="mx-auto flex h-full w-full max-w-6xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex items-center justify-between gap-3 border-b border-slate-200 px-4 py-3"><div className="min-w-0"><p className="truncate font-bold text-slate-950">{visualizando.titulo}</p><p className="truncate text-xs text-slate-500">{visualizando.nome_arquivo}</p></div><div className="flex shrink-0 gap-2"><a href={`/api/documentos-financeiros/${visualizando.id}/arquivo`} target="_blank" rel="noreferrer" className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700">Abrir fora</a><button onClick={()=>setVisualizando(null)} aria-label="Fechar visualizador" className="grid h-9 w-9 place-items-center rounded-lg bg-slate-100 text-xl font-bold text-slate-700">×</button></div></header><iframe title={`Visualização de ${visualizando.titulo}`} src={`/api/documentos-financeiros/${visualizando.id}/arquivo`} className="min-h-0 flex-1 bg-slate-100"/></div></div>}</div></main>;
}
